### ISSUE TITLE
QCustomPlot2 Installation issues

### ISSUE THREAD

**Issue by kksdtty** [nixgnauhcuy/QCustomPlot_Pyqt_Study#1]
I tried to install QCustomPlot2 using pip, but it failed. What should I do?

**Comment by nixgnauhcuy** [comment]
Maybe you can check the `Quick Start` guide or try installing QCustomPlot_PyQt5. They are the same. The command is as follows:
```
pip install QCustomPlot_PyQt5
```

**Comment by nixgnauhcuy** [comment]
If there are still issues, you can reopen it.

**Comment by kksdtty** [comment]
it worked, the problem is solved, thk!
